env_type: realworld

total_num_envs: null

auto_reset: True
ignore_terminations: False
reward_mode: raw
wrap_obs_mode: simple
seed: 0
group_size: 1
use_fixed_reset_state_ids: False
max_steps_per_rollout_epoch: 100
max_episode_steps: 100
no_gripper: False
use_spacemouse: False
use_gello: False
gello_port: null
use_relative_frame: False
main_image_key: "main_camera"
wrist_image_key: "wrist_camera"
default_prompt: "insert the peg in the hole"
task_mode: full_task
critical_phase_key: v
record_prefix_before_critical_phase: false

video_cfg:
  save_video: False
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/train

init_params:
  # Consumes 7D EE delta actions:
  # actions[0:3] normalized xyz delta, actions[3:6] normalized xyz-euler delta,
  # actions[6] gripper command.
  id: "PegInsertionEnv-v1"
  num_envs: null

override_cfg:
  is_dummy: false
  task_description: "insert the peg in the hole"
  target_ee_pose: [0.60283899, -0.30243948, 0.42646784, 2.93922733, -0.03996551, -1.67041543]
  joint_reset_qpos: [0.0677, 0.1155, 0.1334, -1.5898, 0.1972, 2.1341, -0.5112]
  reward_threshold: [0.01, 0.01, 0.01, 0.2, 0.2, 0.2]
  use_dense_reward: false
  reward_scale: 1.0
  enable_gripper_penalty: false
  max_num_steps: 100
